@echo off
echo This is the first test script.
echo Running some tests...
ping 127.0.0.1 -n 2 > nul
echo Running some tests....
timeout /t 1 /nobreak >nul
echo Running some tests.....
timeout /t 1 /nobreak >nul
echo Running some tests......
timeout /t 1 /nobreak >nul
echo Nice
timeout /t 1 /nobreak >nul
echo Running some tests......
timeout /t 1 /nobreak >nul
echo Running some tests......
timeout /t 1 /nobreak >nul
exit